apiVersion: v1
kind: ConfigMap
metadata:
  name: #{service}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{service}#
    app.kubernetes.io/instance: #{service}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{service}#
    app.bancolombia.com.co/env: "#{env}#"
    app.bancolombia.com.co/cost-center: "#{cost-center}#"
    app.bancolombia.com.co/application-code: "#{application-code}#"
    app.bancolombia.com.co/project: "#{project-name}#"
    app.bancolombia.com.co/pmo: "#{pmo}#"
    app.bancolombia.com.co/responsible: #{responsible}#
data:
  ENV: "#{env}#"

